In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Name": ["Suryansh", "Rahul", "Aman", "Priya"],
    "Department": ["AI", "Web", "AI", "Data"],
    "Salary": [60000, 45000, 70000, 65000]
}
df = pd.DataFrame(data)
df

       Name Department  Salary
0  Suryansh         AI   60000
1     Rahul        Web   45000
2      Aman         AI   70000
3     Priya       Data   65000

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        4 non-null      object
 1   Department  4 non-null      object
 2   Salary      4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 224.0+ bytes

             Salary
count      4.000000
mean   60000.000000
std    10801.234497
min    45000.000000
25%    56250.000000
50%    62500.000000
75%    66250.000000
max    70000.000000

In [4]:
ai_team = df[df["Department"] == "AI"]

ai_team

       Name Department  Salary
0  Suryansh         AI   60000
2      Aman         AI   70000

In [5]:
df.sort_values(by="Salary", ascending=False)

       Name Department  Salary
2      Aman         AI   70000
3     Priya       Data   65000
0  Suryansh         AI   60000
1     Rahul        Web   45000

In [6]:
df["Bonus"] = df["Salary"] * 0.10

df

       Name Department  Salary   Bonus
0  Suryansh         AI   60000  6000.0
1     Rahul        Web   45000  4500.0
2      Aman         AI   70000  7000.0
3     Priya       Data   65000  6500.0

In [7]:
df["Salary"].mean()

np.float64(60000.0)

In [8]:
df.groupby("Department")["Salary"].mean()

Department
AI      65000.0
Data    65000.0
Web     45000.0
Name: Salary, dtype: float64

In [9]:
df.loc[2, "Salary"] = None
df

df.isnull().sum()

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df

       Name Department        Salary   Bonus
0  Suryansh         AI  60000.000000  6000.0
1     Rahul        Web  45000.000000  4500.0
2      Aman         AI  56666.666667  7000.0
3     Priya       Data  65000.000000  6500.0